import React, { useMemo } from "react";
import CalendarHeatmap, { HeatmapScaleType } from "./CalHeatmapWrapper";

interface HeatmapDataPoint {
  date: string;
  value: number;
}

const DEFAULT_PNL_COLORS_DARK = [
  "#FF3B3B", "#D62020", "#9C1C1C", "#661515",
  "#1e293b",
  "#0A3824", "#107D47", "#14CE66", "#7CFFB0",
];

export interface HeatmapContainerProps {
  /** Raw daily financial rows — must have `date` and the chosen `metric` field. */
  dailyFinancialData: any[];
  /** Unique DOM id suffix — must be unique per rendered instance. */
  containerId?: string;
  /** CalHeatmap color scale algorithm. Defaults to "symlog". */
  scaleType?: HeatmapScaleType;
  /** Financial field to read values from. Defaults to "netPLExclRebatesAndCharges". */
  metric?: string;
  /**
   * Pre-computed 9-color range array. Generated by buildHeatmapColorRange().
   * Defaults to the classic P&L red/green palette when not provided.
   */
  colorRange?: string[];
  /** Optional group label displayed above the calendar. */
  groupLabel?: string;
  /** Dark mode flag. */
  darkMode?: boolean;
}

function processData(
  rows: any[],
  metric: string,
): { maxAbsoluteValue: number; points: HeatmapDataPoint[] } {
  let maxAbsValue = 100;
  const points: HeatmapDataPoint[] = [];

  for (const row of rows) {
    const val = typeof row[metric] === "number" ? row[metric] : 0;
    if (Math.abs(val) > maxAbsValue) maxAbsValue = Math.abs(val);
    points.push({ date: row.date, value: val });
  }

  const rounded = maxAbsValue % 100 === 0 ? maxAbsValue : Math.ceil(maxAbsValue / 100) * 100;
  return { maxAbsoluteValue: rounded, points };
}

export const HeatmapContainer = React.memo(function HeatmapContainer({
  dailyFinancialData,
  containerId = "default",
  scaleType = "symlog",
  metric = "netPLExclRebatesAndCharges",
  colorRange = DEFAULT_PNL_COLORS_DARK,
  groupLabel,
  darkMode = false,
}: HeatmapContainerProps) {
  const { maxAbsoluteValue, points } = useMemo(
    () => processData(dailyFinancialData ?? [], metric),
    [dailyFinancialData, metric],
  );

  if (!dailyFinancialData?.length) return null;

  return (
    <CalendarHeatmap
      data={points}
      domainRangeLowerLimit={-maxAbsoluteValue}
      domainRangeUpperLimit={maxAbsoluteValue}
      containerId={`cal-heatmap-${containerId}`}
      scaleType={scaleType}
      colorRange={colorRange}
      groupLabel={groupLabel}
      darkMode={darkMode}
    />
  );
});
